# Generated by Django 5.2.8 on 2026-02-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('STARTED', 'Started'), ('COMPLETED', 'Completed')], default='INVITED', max_length=20),
        ),
    ]
